version: '3.8'

services:
  # 1. Theos Landing Page
  theos-landing:
    build:
      context: ./landing
      dockerfile: Dockerfile
    container_name: theos-landing-container
    ports:
      - "4210:80"
    restart: always

  # 2. Theos Portal POPT (Admin)
  theos-portal-popt:
    build:
      context: ./portal-popt
      dockerfile: Dockerfile
    container_name: theos-portal-popt-container
    ports:
      - "4212:80"
    restart: always

  # 3. Theos Portal PAT (Alunos)
  theos-portal-pat:
    build:
      context: ./portal-pat
      dockerfile: Dockerfile
    container_name: theos-portal-pat-container
    ports:
      - "4211:80"
    restart: always
